### ISSUE TITLE
get travis badge showing green

### ISSUE THREAD

**Issue by jgravois** [esripdx/node-arcgis#50]
it says invalid build right now.  perhaps an esripdx admin just needs to flip a switch?

https://travis-ci.org/esripdx/node-arcgis

**Comment by nikolaswise** [comment]
I think so ... @paulcpederson said it was easy! We'll get there. Westing with #52 right now, will get to it after!

Unless someone else want to give it a crack. Anyone?

**Comment by jgravois** [comment]
i have *flipped* the switch, so the next time anyone pushes a commit, the build *should* be triggered

**Comment by nikolaswise** [comment]
Working great!
