### ISSUE TITLE
[website] page load issue

### ISSUE THREAD

**Issue by ngoldman** [esripdx/node-arcgis#62]
Loading is taking about 11 seconds for me (no text visible on page until then). Getting a ton of 403s from fast.fonts.net too.

![screen shot 2016-03-04 at 3 36 35 pm](https://cloud.githubusercontent.com/assets/427322/13543334/2bb91b3a-e21f-11e5-9cdd-1a8a7ad1d3d5.png)

**Comment by nikolaswise** [comment]
Caused by domain whitelisting. Temporarily disabled Avenir untill I can get keys to a real domain.
